### PR TITLE
Add BufferedSource and InputStreamReader as possible resource

### PR DESCRIPTION
**Pull request by gurghet**
This is just so I don't forget since I have to delete this code for now.

### CODE REVIEW

**Comment by dylemma** [comment]
I should probably make `XMLResource` covariant so you can just make a `XMLResource[java.io.Reader]` instead of having to make a specific `XMLResource[InputStreamReader]`. Along the same lines, I wonder if there's some generalization that can be made to support the BufferedSource without having to explicitly code around BufferedSource.

I think I also want to re-evaluate the policy of closing streams from the XMLResource. I think the best practice is that if someone hands you (you = a library) a stream, *they* are responsible for closing that stream. More to the point, whoever opens the stream has the responsibility of closing it. So e.g. my `InputStreamXMLResource` probably shouldn't be trying to close the stream. I think the same idea applies to the two new resources you added.

**Comment by gurghet** [comment]
That was exactly my problem by the way. I use zio which already takes care of resource management, so all the errors there were too deep to catch.

**Comment by dylemma** [comment]
Doh, I forgot to do this when I was setting up the 0.7 release. Will probably make a 0.7.1 for this next time I have a bit of time.

**Comment by dylemma** [comment]
The commit I just pushed adds `XMLResource[Reader]`, and improves the `XMLResource[() => T]` support so you should be able to say `parser.parse(() => source.reader)` rather than having to create an `XMLResource[BufferedReader]`.

**Comment by dylemma** [comment]
It turns out that the underlying javax and jackson parser classes were taking it upon themselves to close the streams, even if my `XMLResource` was not. I made some changes to prevent this for the InputStream/Reader resources, but still have them close for the `() => T` resource.

That and the change to make the resource types contravariant have been released as version 0.8. That should be everything brought up in this thread, so I'll go ahead and close it.

**Pull request closed without merging**
